version: '2'
services:
    productservice-app:
        image: productservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://productservice-mysql:3306/productservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    productservice-mysql:
        extends:
            file: mysql.yml
            service: productservice-mysql
